### ISSUE TITLE
Privacy manifest missing in CocoaPods integration

### ISSUE THREAD

**Issue by dmazzoni** [hyperwallet/hyperwallet-ios-sdk#143]
The privacy manifest file has been introduced, but as it is not being referenced in the SDK's Podspec it will not be packaged with apps that integrate the SDK with CocoaPods.

In order for the SDK's privacy manifest file to be correctly integrated, the Podspec should define a resource bundle that includes it as follows:

```
spec.resource_bundles = {'HyperwalletSDK' => ['Sources/PrivacyInfo.xcprivacy']}
```

**Comment by grmeyer-hw-dev** [comment]
Hi @dmazzoni 
Thanks for reporting this issue the fix will be available on `1.0.0-beta20`
