### ISSUE TITLE
Missing required reasons API declaration in privacy manifest

### ISSUE THREAD

**Issue by dmazzoni** [hyperwallet/hyperwallet-ios-sdk#144]
The SDK [uses](https://github.com/hyperwallet/hyperwallet-ios-sdk/blob/ad09917da0d92ea668c951f2aee12edbc9e6661c/Sources/Configuration.swift#L40) the [`systemUptime`](https://developer.apple.com/documentation/foundation/processinfo/1414553-systemuptime) API, which is [listed by Apple](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394) among the APIs that require a reason to be declared for their usage in the privacy manifest.

**Comment by TyDaGoa** [comment]
access_token$sandbox$rczzxhqdvbnfz985$b1deec7f11c90eeeabd9524d645cd94a

**Comment by grmeyer-hw-dev** [comment]
Hi @dmazzoni 
Thanks for reporting this issue the fix will be available on `1.0.0-beta20`
